[package]
name = "server"
version = "0.1.0"
authors = ["Jean Arhancetebehere <jean.arhancetebehere@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
juniper = "0.11.1"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"